name = "flyingclubreservations"
compatibility_date = "2024-04-16"
main = "api/worker.js"

[[d1_databases]]
binding = "DB"
database_name = "flying-club-db"
database_id = "bd0a3c07-e433-4799-b92f-636d8ef5a1b7"

[functions]
directory = "./functions"
external_node_modules = ["@cloudflare/ai"]
external_node_modules = ["luxon"]


[build]
upload.format = "directory"
upload.dir = "build"

[pages]
build_output_dir = "./build"